name: Latest blog post
on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pull-latest-blog-posts:
    name: Update with latest blog post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@sirajul.anik"
          max_post_count: 5
